### ISSUE TITLE
07--Virtual-Pet--Jason

### ISSUE THREAD

**Issue by jkirouac42** [wcci-summer-2016/course-resources#106]
# Week 2

- Intro to OOP
- Lists and Dictionaries
- Building Classes - Methods and Properties
- StringBuilder and RegEx

## Tasks

- Day 1 (Lab Day from week 1 project)
- Day 2 (Intro to OOP)
  - [ ] Chapter 15
  - [ ] Chapter 17
  - [ ] Chapter 18
  - [ ] Chapter 19
  - [ ] Assignment: [Dragon Slaying (Part 1)](assignments/01-dragon-slaying-pt1)
- Day 3 (Class canceled)
- Day 4 (Building Classes, Methods and Properties)
  - [ ] Chapter 15 (read/skim it again!)
  - [ ] Chapter 18 (read/skim it again!)
- Day 5
  - [ ] Project: [Virtual Pet](project-virtual-pet)
