### ISSUE TITLE
09 -- Express Yourself -- Prince

### ISSUE THREAD

**Issue by princecode** [wcci-summer-2016/course-resources#125]
# Week 3

- Inheritance
- Regular Expressions
- Polymorphism, Virtual Methods, Abstract Classes
- Interfaces, Lists and Dictionaries
- Exceptions and File I/O

## Tasks

- Day 1 (Lab Day)
- Day 2 (Inheritance, Regular Expressions)
  - [ ] Chapter 21
  - [ ] Assignment: [Express Yourself](assignments/01-express-yourself)
- Day 3 (Polymorphism, Virtual Methods, Abstract Classes)
  - [ ] Chapter 22
  - [ ] Assignment: [Library (Part 1)](assignments/02-library-pt1)
- Day 4 (Interfaces, Lists, and Dictionaries)
  - [ ] Chapter 23
  - [ ] Chapter 24
  - [ ] Assignment: [Library (Part 2)](assignments/02-library-pt1)
- Day 5 (Project Day)
  - [ ] Project: TBD
