### ISSUE TITLE
Structure--Jason

### ISSUE THREAD

**Issue by jkirouac42** [wcci-summer-2016/course-resources#183]
# Week 4

- HTML
- CSS
- Bootstrap

## Tasks

- Day 1 (HTML)
  - [ ] [W3Schools HTML Tutorial](http://www.w3schools.com/html/)
    - [ ] [HTML Introduction](http://www.w3schools.com/html/html_intro.asp)
    - [ ] [HTML Basic](http://www.w3schools.com/html/html_basic.asp)
    - [ ] [HTML Elements](http://www.w3schools.com/html/html_elements.asp)
    - [ ] [HTML Attributes](http://www.w3schools.com/html/html_attributes.asp)
  - [ ] Homework: [Structure](assignments/01-structure)
- Day 2 (CSS)
  - [ ] [W3Schools CSS Tutorial](http://www.w3schools.com/css/)
    - [ ] [CSS Introduction](http://www.w3schools.com/css/css_intro.asp)
    - [ ] [CSS Syntax](http://www.w3schools.com/css/css_syntax.asp)
    - [ ] [CSS How To](http://www.w3schools.com/css/css_howto.asp)
    - [ ] [CSS Colors](http://www.w3schools.com/css/css_colors.asp)
  - [ ] Homework: TBD
- Day 3 (Bootstrap)
  - [ ] [W3Schools Bootstrap 3 Tutorial](http://www.w3schools.com/bootstrap/)
    - [ ] [BS Get Started](http://www.w3schools.com/bootstrap/bootstrap_get_started.asp)
    - [ ] [BS Grid Basic](http://www.w3schools.com/bootstrap/bootstrap_grid_basic.asp)
  - [ ] Homework: TBD
- Day 4 (Project Day)
  - [ ] Project: TBD
