### ISSUE TITLE
02 -- Go with the Flow -- William

### ISSUE THREAD

**Issue by Echarger1** [wcci-summer-2016/course-resources#27]
# Tasks

### Required Tasks

- [ ] Yak Shaving
  - [ ] Open a new issue in the `course-resources` repository called `02 -- Go with the Flow -- Your Name`, and copy/paste these tasks into the description
  - [ ] Create a new Console application project in Visual Studio called `GoWithTheFlow`, and make sure to check **Create a new Git repository**.
  - [ ] Create a remote repository on GitHub.com called `02-go-with-the-flow`
  - [ ] Set up your local repository to track with the remote repository
  - [ ] Make frequent commits with descriptive messages
- [ ] Gather Requirements
  - [ ] Find or create a flowchart that doesn't involve any loops
- [ ] Write Code
  - [ ] Translate the flowchart logic into code
- [ ] Submit
  - [ ] Fill out the homework submission Google form with a link to the issue and a link to your GitHub repository

### Stretch Tasks

- [ ] Translate a more complicated flowchart
- [ ] Use `goto` to handle flowcharts that repeat/loop
- [ ] Be flexible about input
